# Generated by Django 5.1.7 on 2025-04-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='user',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
