# Generated by Django 5.1.7 on 2025-04-05 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_reminder_user_alter_reminder_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='reminder',
            name='time',
            field=models.TimeField(default="12:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reminder',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.priority'),
        ),
    ]
