# Generated by Django 5.1.7 on 2025-04-05 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_priority_reminder_time_reminder_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='priority',
        ),
        migrations.AddField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
