# Generated by Django 5.1.7 on 2025-04-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_reminder_priority_reminder_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Priority',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(max_length=10),
        ),
    ]
